### ISSUE TITLE
How to enable preview?

### ISSUE THREAD

**Issue by mgajda** [bvautour/language-twee2#1]
I have just installed `language-twee2`, and do not see preview in Atom.
There is no mention of it in `Packages` menu, nor in `README.md`.

Can you document how did you achieve preview?

**Comment by bvautour** [comment]
Hey thanks for taking interest in my little project. Could you clarify what you mean by preview?

**Comment by mgajda** [comment]
I mean whatever you show in the [README docs animation](https://camo.githubusercontent.com/b2b014e0467466f2a3814fc2ccdbd97db0fc7e88/687474703a2f2f692e696d6775722e636f6d2f57554d426152322e676966)

I thought the animation is demonstrating functionality of your package, does it not?

**Comment by bvautour** [comment]
I understand now. You're looking for preview plus.
https://atom.io/packages/preview-plus

**Comment by mgajda** [comment]
I installed it, but did not find how to configure Twine or Twee2 with it.
Can you kindly provide your config?

**Comment by bvautour** [comment]
Sure, you need to compile your twee2 file to html, open that html file and preview that.
